version: '3'

services:
  kevin_mode_api:
    build: .
    command: python main.py
    depends_on:
      - postgres
    volumes:
      - .:/code
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
#      DATABASE_URL: "postgresql+psycopg2://postgres@postgres:5432/postgres"
    ports:
      - "5000:5000"
    restart: always
  postgres:
    image: postgres:11.1-alpine
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: always

